# Quick Fix for Android Build Issues

Write-Host "🔧 Fixing Android build issues..." -ForegroundColor Green

# Fix 1: Create capacitor.settings.gradle
Write-Host "`n✅ Creating capacitor.settings.gradle..." -ForegroundColor Cyan
$capacitorSettings = @"
// DO NOT EDIT THIS FILE! It is generated each time gradle is run
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android')
"@
$capacitorSettings | Out-File -FilePath "android\capacitor.settings.gradle" -Encoding UTF8 -Force

Write-Host "✅ Fixed!" -ForegroundColor Green
Write-Host "`nNow run:" -ForegroundColor Yellow
Write-Host "1. npm run build" -ForegroundColor White
Write-Host "2. npx cap sync android" -ForegroundColor White
Write-Host "3. npx cap open android" -ForegroundColor White
